version: '3'

services:
  nats:
    image: nats
    restart: unless-stopped
    entrypoint: /nats-server
    command: "-D -V --config /config/jetstream.conf"
    ports:
      - "${NATS_PORT}:4222"
    volumes:
      - ./_data/nats/data:/data
      - ./nats/jetstream.conf:/config/jetstream.conf

  pg:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./_data/pg/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # pgadmin:
  #   image: dpage/pgadmin4:8
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pg@admin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #     PGADMIN_LISTEN_PORT: 9656
  #   ports:
  #     - "9656:9656"
  #   volumes:
  #     - ./_data/pgadmin:/var/lib/pgadmin

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server --address :10123 --console-address ":10124" /data/minio
    expose:
      - "${MINIO_SERVER_PORT}"
      - "${MINIO_CONSOLE_PORT}"
    ports:
      - "${MINIO_SERVER_PORT}:10123"
      - "${MINIO_CONSOLE_PORT}:10124"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:10123/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./_data/minio:/data

  redis:
    image: redis:6
    restart: unless-stopped
    expose:
      - "${REDIS_PORT}"
