networks:
  app-network:
    name: manuspect-net
    external: true

services:
  collector-go:
    env_file:
      - ../.env
    image: debian:12-slim
    restart: no
    command: >
      sh -c "collector_go"
    volumes:
      - ./bin/collector_go:/usr/bin/collector_go
      - ./docs/:/docs
    networks:
      - app-network
