// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package databasesqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUserDb(ctx context.Context, arg CreateUserDbParams) (CreateUserDbRow, error)
	DeleteRefreshTokenDb(ctx context.Context, id int32) error
	DeleteUserDb(ctx context.Context, id uuid.UUID) (DeleteUserDbRow, error)
	EditPassword(ctx context.Context, arg EditPasswordParams) error
	GetRefreshTokensDb(ctx context.Context) ([]Token, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserIdByEmail(ctx context.Context, email string) (uuid.UUID, error)
	GetUsersDb(ctx context.Context) ([]GetUsersDbRow, error)
	IsCreatedRefreshTokenDb(ctx context.Context, userID uuid.UUID) (string, error)
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (Token, error)
	UpdateRefreshTokenDb(ctx context.Context, arg UpdateRefreshTokenDbParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UserByIdDb(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
